
[functions.Certificate-Issuance]
enabled = true
verify_jwt = true
import_map = "./functions/Certificate-Issuance/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/Certificate-Issuance/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/Certificate-Issuance/*.html" ]

[functions.Verify-Certificate]
enabled = true
verify_jwt = true
import_map = "./functions/Verify-Certificate/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/Verify-Certificate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/Verify-Certificate/*.html" ]
